# -*- Makefile -*-

GOARCH = 6
GOCC = $(GOARCH)g
GOLINK = $(GOARCH)l

name = foo_program
objects = $(name).$(GOARCH) some_other.$(GOARCH)

.PHONY: default
default: $(name)

$(objects): %.$(GOARCH)	: %.go
	$(GOCC) $<

$(name): $(objects)
	$(GOLINK) $(objects)
	mv $(GOARCH).out $(name)

test:	$(name)
	gotest

.PHONY: clean
clean:
	rm -f $(objects) $(name)
