# -*- Makefile -*-
#
# A custom Makefile. There is a standard way of writing Makefiles for Go
# apps and packages that uses the include files that come with Go, but I
# wrote this before I had read about those.

GOARCH = 6
GOCC = $(GOARCH)g
GOLINK = $(GOARCH)l

name = foo_program
objects = $(name).$(GOARCH) some_other.$(GOARCH)

.PHONY: default
default: $(name)

$(objects): %.$(GOARCH)	: %.go
	$(GOCC) $<

$(name): $(objects)
	$(GOLINK) $(objects)
	mv $(GOARCH).out $(name)

test:	$(name)
	gotest

.PHONY: clean
clean:
	rm -f $(objects) $(name)
